version: "3.8"
services:
  myapp:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: myapp:django
    container_name: new_django_container
    command: python manage.py runserver 0.0.0.0:8001