version: "3.8"
services:
  myapp:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: myapp:django
    container_name: new_django_container
    command: python manage.py runserver 0.0.0.0:8001
    restart: always
    networks:
      - web_default

    depends_on:
      - db
  db:
    image: mysql
    networks:
      - web_default
    container_name: db
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql


networks:
  web_default:
    driver: bridge