# Generated by Django 4.1.4 on 2022-12-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_questions_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, verbose_name='Имя отвечающего')),
                ('text', models.TextField(null=True, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.questions')),
            ],
            options={
                'verbose_name': 'Ответы',
                'ordering': ('created',),
            },
        ),
    ]
