# Generated by Django 4.1.4 on 2022-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_commets_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',), 'verbose_name': 'Ответы'},
        ),
    ]
