# Generated by Django 4.1.4 on 2023-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_questions_q_cat_questions_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
