# Generated by Django 4.1.4 on 2022-12-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comments_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Answer',
        ),
    ]
