# Generated by Django 4.1.4 on 2023-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_questions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='URL'),
        ),
    ]
