# Generated by Django 4.1.4 on 2023-01-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_answer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created',), 'verbose_name': 'Ответы'},
        ),
    ]
