# Generated by Django 4.1.4 on 2022-12-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя отвечающего'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.questions'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
    ]
