# Generated by Django 4.1.4 on 2022-12-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_answer'),
        ('blog', '0008_alter_answer_created_alter_answer_name_and_more'),
    ]

    operations = [
    ]
