# Generated by Django 4.1.4 on 2022-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_answer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_text',
            field=models.TextField(blank=True, default='Текст', null=True, verbose_name='Контент'),
        ),
    ]
