# Generated by Django 4.1.4 on 2023-01-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_answer_options_answer_parent_alter_answer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, default='Запись была удалена', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.answer', verbose_name='Родитель'),
        ),
    ]
