# Generated by Django 4.1.4 on 2022-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_answer_name_alter_answer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_text',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
