# Generated by Django 4.1.4 on 2022-12-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_questions_q_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория'),
        ),
    ]
