# Generated by Django 4.1.4 on 2023-01-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_answer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.answer', verbose_name='Родитель'),
        ),
    ]
