# Generated by Django 4.1.4 on 2023-01-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_answer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.answer', verbose_name='Родитель'),
        ),
    ]
