# Generated by Django 4.1.4 on 2023-01-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_answer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_helped',
            field=models.BooleanField(default=False),
        ),
    ]
