# Generated by Django 4.1.4 on 2023-01-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_answer_is_helped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_helped',
        ),
    ]
