# Generated by Django 4.1.4 on 2022-12-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_text',
            field=models.TextField(default='', verbose_name='Контент'),
        ),
    ]
