# Generated by Django 4.1.4 on 2023-01-14 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_remove_answer_is_helped'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('pressed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('question_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.questions', verbose_name='Лайк к вопросу')),
            ],
            options={
                'verbose_name': 'Правильные ответы',
            },
        ),
    ]
