# Generated by Django 4.1.4 on 2023-01-14 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_helpedanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpedanswer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='helpedanswer',
            name='pressed_by',
        ),
        migrations.RemoveField(
            model_name='helpedanswer',
            name='question_post',
        ),
        migrations.AddField(
            model_name='helpedanswer',
            name='counter',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
