# Generated by Django 4.1.4 on 2023-01-14 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_remove_helpedanswer_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpedanswer',
            old_name='counter',
            new_name='like_answer',
        ),
        migrations.AddField(
            model_name='helpedanswer',
            name='dislike_answer',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
