# Generated by Django 4.1.4 on 2023-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_difficult_questions_difficult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficult',
            field=models.IntegerField(choices=[(1, 'Сложноый'), (2, 'Средний'), (3, 'Легкий')], default=3),
        ),
        migrations.DeleteModel(
            name='Difficult',
        ),
    ]
