# Generated by Django 4.1.4 on 2023-01-21 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_questions_difficult_delete_difficult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория_вопроса')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.difficult', verbose_name='Категория'),
        ),
    ]
