# Generated by Django 4.1.4 on 2023-01-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_questions_difficult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='slug',
        ),
    ]
