# Generated by Django 4.1.4 on 2023-01-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_questions_difficult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficult',
            field=models.CharField(choices=[('E', 'Легкий'), ('M', 'Средний'), ('D', 'Сложный')], default='E', max_length=1),
        ),
    ]
