# Generated by Django 4.1.4 on 2023-01-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_questions_difficult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficult',
        ),
    ]
