# Generated by Django 4.1.4 on 2023-01-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_delete_difficult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpedAnswer',
        ),
    ]
