# Generated by Django 4.1.4 on 2023-03-08 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0040_alter_answer_text_alter_questions_q_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='decided',
            field=models.ManyToManyField(related_name='decided_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
