# Generated by Django 4.1.4 on 2023-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=True),
        ),
    ]
