# Generated by Django 4.1.4 on 2023-01-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_myuserprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание профиля пользователя'),
        ),
        migrations.AlterField(
            model_name='myuserprofile',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='myuserprofile',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users_photo/%Y/%m/%d'),
        ),
    ]
