# Generated by Django 4.1.4 on 2022-12-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
