# Generated by Django 4.1.4 on 2023-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_myuserprofile_bio_alter_myuserprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='myuserprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photo/%Y/%m/%d'),
        ),
    ]
