# Generated by Django 4.1.4 on 2023-01-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_myuserprofile_name_alter_myuserprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuserprofile',
            name='name',
        ),
    ]
