# Generated by Django 4.1.4 on 2022-12-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_customuser_delete_profile'),
        ('user_profile', '0006_profile_delete_userprofile'),
    ]

    operations = [
    ]
