# Generated by Django 4.1.4 on 2023-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_myuserprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserprofile',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
