# Generated by Django 4.1.4 on 2022-12-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20221221_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
