# Generated by Django 4.1.4 on 2023-01-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_myuserprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuserprofile',
            name='name',
        ),
    ]
